export const PAYMENT_STATUS_PENDING = "PENDING";
export const PAYMENT_STATUS_COMPLETED = "COMPLETED";
export const PAYMENT_STATUS_FAILED = "FAILED";
export const PAYMENT_STATUS_REFUNDED = "REFUNDED";
export const PAYMENT_STATUS_SUCCESS = "SUCCESS";