export const HOME_ROUTE = "/"
export const ABOUT_ROUTE = "/about"
export const PRODUCTS_ROUTE = "/products"
export const CONTACT_ROUTE = "/contact"
export const LOGIN_ROUTE = "/login"
export const REGISTER_ROUTE = "/register"
export const FORGOT_PASSWORD_ROUTE = "/forgot-password"
export const REST_PASSWORD_ROUTE = "/reset-password"