import Footer from "@/components/Footer";
import "./globals.css";
import React from "react";
import Header from "@/components/Header";
import { config } from "@/config/config";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Header />

        <main className="flex-1">{children}</main>
         <Toaster
          toastOptions={{
            duration: 3000,
            style: {
              fontSize: "14px",
            },
          }}
        />
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
