import Footer from "@/components/Footer";
import "./globals.css";
import React from "react";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import { config } from "@/config/config";
import AppProvider from "@/redux/provider";
import MainLayout from "@/layouts/MainLayout";
import CartDrawer from "@/components/CartDrawer";

export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <MainLayout>
            <Header />
            <CartDrawer/>
            <main className="flex-1">{children}</main>
            <Toaster
              toastOptions={{
                duration: 3000,
                style: {
                  fontSize: "14px",
                },
              }}
            />
            <Footer />
          </MainLayout>
        </AppProvider>
      </body>
    </html>
  );
};

export default RootLayout;
