import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Nexora",
  description: "Generated by create next app",
};

import React from "react";
import Header from "@/components/Header";

const RootLayout = ({ children }) => {
  return (
    <html>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
