import React from "react";
import ProductCard from "../../components/ProductCard";
import ProductFilter from "../../components/ProductFilter";
import { getProducts } from "@/api/product";
import EmptyState from "@/components/EmptyState";

export const metadata = {
  title: "Products | Nexora",
  description: "Generated by create next app",
};

const ProductsPage = async ({ searchParams }) => {
  const products = await getProducts(searchParams);

  return (
    <section className="container-page py-16 bg-paper dark:bg-[#0e0f12] transition-colors duration-300">
      <div className="grid lg:grid-cols-[250px_1fr] gap-8">
        <ProductFilter />

        {products.length === 0 ? (
          <EmptyState
            title="No matches"
            description="Nothing fits those filters yet. Try widening the price range or clearing a filter."
            action={<button className="btn-secondary">Oops!</button>}
          />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
            {products.map((product) => (
              <ProductCard key={product._id} product={product} />
            ))}
          </div>
        )}
      </div>
    </section>
  );
};

export default ProductsPage;