import { config } from "@/config/config";
import axios from "axios";
import React from "react";
import ProductCard from "../_components/ProductCard";
import { SlidersHorizontal } from "lucide-react";
import ProductFilter from "../_components/ProductFilter";
import ProductSort from "../_components/ProductSort";
import { DEFAULT_SORT } from "@/constants/Defaults";

export const metadata = {
  title: "Products | Nexora",
  description: "Generated by create next app",
};

const ProductsPage = async ({ searchParams }) => {
  const sort = (await searchParams)?.sort ?? DEFAULT_SORT;
  
  const response = await axios.get(
    `${config.apiUrl}/api/v1/products?sort=${sort}`,
  );

  const products = response.data;

  return (
    <section className="container-page py-16">
      <ProductSort />

      <div className="grid lg:grid-cols-[220px_1fr] gap-8">
        <aside className={`block lg:block`}>
          <ProductFilter />
        </aside>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
          {products.map((product) => (
            <ProductCard key={product._id} product={product} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default ProductsPage;
