import React from "react";
import ProductCard from "../_components/ProductCard";
import ProductFilter from "../_components/ProductFilter";
import { getProducts } from "@/api/product";

export const metadata = {
  title: "Products | Nexora",
  description: "Generated by create next app",
};

const ProductsPage = async ({ searchParams }) => {
  const products = await getProducts(searchParams);

  return (
    <section className="container-page py-16">
      <div className="grid lg:grid-cols-[250px_1fr] gap-8">
        <aside className={`block lg:block`}>
          <ProductFilter />
        </aside>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2">
          {products.map((product) => (
            <ProductCard key={product._id} product={product} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default ProductsPage;
