import React from 'react'
export const metadata = {
  title: "About | Nexora",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
    <div>AboutPage</div>
  )
}

export default AboutPage